# Generated by Django 3.2.6 on 2021-08-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='atividades_secundarias',
            field=models.JSONField(default='a'),
            preserve_default=False,
        ),
    ]
