# Generated by Django 3.2.6 on 2021-08-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empresas_atividades_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='data_abertura',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
