# Generated by Django 3.2.6 on 2021-08-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empresas_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='atividades_secundarias',
            field=models.TextField(),
        ),
    ]
